databases:
  - name: TACKLEMASTER_DB
    databaseName: tacklemaster_db
    user: rei
    region: singapore

services:
  - type: web
    name: TackleMaster
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TACKLEMASTER_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
